# Generated by Django 4.0 on 2022-01-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='converted',
            field=models.BooleanField(default=False),
        ),
    ]
