# Generated by Django 4.0 on 2021-12-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_contract'),
        ('contracts', '0004_contract_remove_contracts_client_and_more'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
    ]
