# Generated by Django 4.0 on 2021-12-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customers_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sales_contract',
        ),
    ]
