# Generated by Django 4.0 on 2022-01-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_converted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='converted',
        ),
    ]
