# Generated by Django 4.0 on 2022-01-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_converted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='sales_contract',
            new_name='sales_contact',
        ),
    ]
