# Generated by Django 4.0 on 2021-12-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers', '0003_remove_customer_sales_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sales_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
