# Generated by Django 4.0 on 2022-01-23 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('contracts', '__first__'),
        ('customers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.TextField(choices=[('on_going', 'On going'), ('finished', 'Finished')])),
                ('attendees', models.IntegerField(default=0)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, max_length=2500)),
                ('contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='customers.customer')),
                ('support_contact', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Support'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
