# Generated by Django 4.0 on 2022-01-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_support_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contract',
        ),
    ]
