# Generated by Django 4.0 on 2021-12-21 11:49

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('payment_due', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
