# Generated by Django 4.0 on 2021-12-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='sales_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
