# Generated by Django 4.0 on 2021-12-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='status',
            field=models.BooleanField(verbose_name=(('on_going', 'on_going'), ('finished', 'finished'))),
        ),
    ]
