# Generated by Django 4.0 on 2021-12-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_contract'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers', '0002_rename_customers_customer_and_more'),
        ('contracts', '0004_contract_remove_contracts_client_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contracts',
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sales_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
