# Generated by Django 4.0 on 2021-12-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_delete_contracts_contract_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=None),
        ),
    ]
