# Generated by Django 4.0 on 2022-01-08 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='client',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
